/**
*****************************************************************************************
*     Copyright (C) 2020  Seeed Technology Co.,Ltd. All rights reserved.
*****************************************************************************************
   * @file      ble_server.c
   * @brief     
   * @author    Hongtai.Liu
   * @date      2020-08-26
   * @version   v1.0
   **************************************************************************************
   * @attention
   * <h2><center>&copy; COPYRIGHT 2020 Seeed Technology Co.,Ltd</center></h2>
   **************************************************************************************
  */

/** Add Includes here **/
#include <bt_flags.h>
#include <string.h>
#include <os_mem.h>
#include <ble_server.h>

void write_post_callback(uint8_t conn_id, T_SERVER_ID service_id, uint16_t attrib_index,
                         uint16_t length, uint8_t *p_value)
{
   (void)p_value;
   log_d("write_post_callback: conn_id %d, service_id %d, attrib_index 0x%x, length %d",
         conn_id, service_id, attrib_index, length);
}

/**
 * @brief read characteristic data from service.
 *
 * @param service_id          ServiceID of characteristic data.
 * @param attrib_index        Attribute index of getting characteristic data.
 * @param offset              Used for Blob Read.
 * @param p_length            length of getting characteristic data.
 * @param pp_value            data got from service.
 * @return Profile procedure result
*/
T_APP_RESULT ble_service_attr_read_cb(uint8_t conn_id, T_SERVER_ID service_id,
                                      uint16_t attrib_index, uint16_t offset, uint16_t *p_length, uint8_t **pp_value)
{
   T_APP_RESULT cause = APP_RESULT_SUCCESS;
   log_d("ble_service_attr_read_cb");
   return (cause);
}

/**
 * @brief write characteristic data from service.
 *
 * @param conn_id
 * @param service_id        ServiceID to be written.
 * @param attrib_index      Attribute index of characteristic.
 * @param length            length of value to be written.
 * @param p_value           value to be written.
 * @return Profile procedure result
*/
T_APP_RESULT ble_service_attr_write_cb(uint8_t conn_id, T_SERVER_ID service_id,
                                       uint16_t attrib_index, T_WRITE_TYPE write_type, uint16_t length, uint8_t *p_value,
                                       P_FUN_WRITE_IND_POST_PROC *p_write_ind_post_proc)
{
   log_d("ble_service_attr_write_cb write_type = 0x%x", write_type);
   *p_write_ind_post_proc = write_post_callback;
   T_APP_RESULT cause = APP_RESULT_SUCCESS;
   return cause;
}

/**
 * @brief update CCCD bits from stack.
 *
 * @param conn_id           connection id.
 * @param service_id          Service ID.
 * @param index          Attribute index of characteristic data.
 * @param cccbits         CCCD bits from stack.
 * @return None
*/
void ble_service_cccd_update_cb(uint8_t conn_id, T_SERVER_ID service_id, uint16_t index, uint16_t cccbits)
{
   log_d("ble_service_cccd_update_cb");
   return;
}

/**
 * @brief ble Service Callbacks.
*/
const T_FUN_GATT_SERVICE_CBS ble_service_cbs = {
    ble_service_attr_read_cb,  // Read callback function pointer
    ble_service_attr_write_cb, // Write callback function pointer
    ble_service_cccd_update_cb // CCCD update callback function pointer
};

/**
  * @brief Add BLE service to the BLE stack database.
  *
  * @param[in]  p_func  Callback when service attribute was read, write or cccd update.
  * @return Service id generated by the BLE stack: @ref T_SERVER_ID.
  * @retval 0xFF Operation failure.
  * @retval others Service id assigned by stack.
  *
  */
T_SERVER_ID ble_add_service(const T_ATTRIB_APPL *ble_service_tbl, uint16_t length)
{
   T_SERVER_ID service_id = 0xff;
   if (false == server_add_service(&service_id,
                                   (uint8_t *)ble_service_tbl,
                                   length,
                                   ble_service_cbs))
   {
      log_e("simp_ble_service_add_service: failure");
      service_id = 0xff;
   }else{
       log_e("simp_ble_service_add_service: success");
   }
   
   return service_id;
}

bool ble_server_init(uint8_t num)
{
    if(num > BLE_SERVER_MAX_APPS)
        return false;
    server_init(num);

    return true;
}
