/*
 * Generated by erpcgen 1.7.4 on Thu Aug 13 11:24:13 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_rpc_ble_callback_h_)
#define _rpc_ble_callback_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10704 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

// Aliases data types declarations
typedef struct binary_t binary_t;

// Structures/unions data types declarations
struct binary_t
{
    uint8_t * data;
    uint32_t dataLength;
};


#endif // ERPC_TYPE_DEFINITIONS

/*! @brief rpc_ble_callback identifiers */
enum _rpc_ble_callback_ids
{
    krpc_ble_callback_service_id = 1,
    krpc_ble_callback_rpc_ble_handle_gap_msg_id = 1,
    krpc_ble_callback_rpc_ble_gap_callback_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name rpc_ble_callback
//@{
void rpc_ble_handle_gap_msg(const binary_t * gap_msg);

void rpc_ble_gap_callback(uint8_t cb_type, const binary_t * cb_data);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _rpc_ble_callback_h_
