/*
 * Generated by erpcgen 1.7.4 on Fri Sep 18 15:38:09 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "rpc_wifi_api_server.h"
#include <new>
#include "erpc_port.h"
#include "erpc_manually_constructed.h"

#if 10704 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif

static ManuallyConstructed<rpc_wifi_drv_service> s_rpc_wifi_drv_service;



// Call the correct server shim based on method unique ID.
erpc_status_t rpc_wifi_drv_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory)
{
    switch (methodId)
    {
        case krpc_wifi_drv_test_id:
            return test_shim(codec, messageFactory, sequence);

        default:
            return kErpcStatus_InvalidArgument;
    }
}

// Server shim for test of rpc_wifi_drv interface.
erpc_status_t rpc_wifi_drv_service::test_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;


    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (!err)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        test();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (!err)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, krpc_wifi_drv_service_id, krpc_wifi_drv_test_id, sequence);

        err = codec->getStatus();
    }

    return err;
}

erpc_service_t create_rpc_wifi_drv_service()
{
    s_rpc_wifi_drv_service.construct();
    return s_rpc_wifi_drv_service.get();
}

void destroy_rpc_wifi_drv_service()
{
    s_rpc_wifi_drv_service.destroy();
}
